### ISSUE TITLE
Pronto Hex

### ISSUE THREAD

**Issue by mavris** [davorf/BlackBeanControl#21]
#Hi,
This is not an "issue", cause BlackBeanControl works just fine.
I was wondering how to make the BlackBeanControl to send a Pronto Hex signal like the below:
`0000 006d 0022 0002 0157 00ac 0015 0016 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0689 0157 0056 0015 0e94`
I tried but it responds with error about the number of digits. Is there any way to convert this so BlackBeanControl would send it?

**Comment by adrianmihalko** [comment]
this would be great

**Comment by davorf** [comment]
Hello!

Since RM3 accepts encrypted payload, it should be encrypted with the same Key and IV the script and the Broadlink Python package are using. Besides that, I'm pretty sure that RM3 payload contains parts that are specific to the unit used, so it would be pretty hard to convert a generic IR code to RM3 acceptable format. If you are familiar with Python, you could try to extract parts of this script and Broadlink package, and use it to encrypt this payload, but, honestly, it's a long shot. Do you have a way to send this command using official Broadlink application? If so, you could intercept network packages, and use that stream in the script .ini file. 

Best regards,
Davor

**Comment by davorf** [comment]
Hello!

Since there wasn't any changes regarding this issue, I will close it. If you have any other questions or suggestions, feel free to open a new one.

Best regards,
Davor
