### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by samsonrosen** [davorf/BlackBeanControl#23]
Hello!

I have been using this tool perfectly for several months but I am suddenly getting the error:

`Church-Server:~ churchserver$ python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c PowerToshiba
Traceback (most recent call last):
  File "/Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py", line 3, in <module>
    import broadlink, configparser
`

**Comment by davorf** [comment]
Hello!

Firstly, sorry for the late response. It looks like some package have changed. Have you uninstalled/reinstalled python-broadlink or configparser packages? If you used newer version of python-broadlink package, it could be due to changes in that package, that are no longer compatible with this script. It happened already, when they've changed a way it encrypts/decrypts payloads. 

Best regards,
Davor

**Comment by startpro** [comment]
Hi! Hello, BlackBeanControl.py running support python2.7 does not support python3. STR compile hex error, can help to modify the BlackBeanControl.py script?. Thank you
