### ISSUE TITLE
BlackBeanControl.py script does not support python3

### ISSUE THREAD

**Issue by startpro** [davorf/BlackBeanControl#28]
Hi! Hello
 BlackBeanControl.py running support python2.7 does not support python3. STR compile hex error, can help to modify the BlackBeanControl.py script
Thank you

**Comment by startpro** [comment]
python3error:DecodedCommand=CommandFromSettings.decode('hex')

**Comment by davorf** [comment]
Hello!

Sorry, but the script is made for Python 2 and I really don't have any free time to adapt and test it in Python 3. You can create a pull request with necessary changes for Python 3 support if you want. But, if you are going to do that, please test it with both, Python 2 and Python 3 before creating a pull request, because a lot of us use it with Python 2, and need Python 2 support too. 

Best regards,
Davor

**Comment by frostworx** [comment]
I use a custom version of BlackBeanControl (great program) which I just wanted to upgrade to python3.
this is not a real fix and therefore not worth a pull request (especially as it probably won't work with python2), but you can use 
    DecodedCommand = binascii.unhexlify(CommandFromSettings)
instead of
    DecodedCommand = CommandFromSettings.decode('hex')
which works fine with python3
